import SwiftUI

/// Settings sub-screens reachable via `minis://settings/<path>`.
/// Mirrors Android's `Routes.*` constants in `DeepLinkHandler.kt` so a
/// link generated by the agent on either platform navigates to the
/// matching screen on the other.
enum SettingsDeepLinkTarget: Equatable {
    case home
    case providers
    case providerDetail(instanceId: String)
    case modelGroups
    case modelGroupDetail(groupId: String)
    case usage
    case skills
    /// [T-ios-assistant-header-open-soul] Soul settings (SOUL.md identity:
    /// name, icon, style, personality body). Reachable as
    /// `minis://settings/soul`, and used by the assistant identity row in the
    /// chat transcript.
    case soul
    case memory
    case storage
    case mountedFolders
    case sharedFolders
    case logs
    case appearance
    case background
    case about
    case permissions
    case environments
    /// [T-mcp-oauth-deeplink] MCP Integrations list / a specific server's
    /// edit form (where the Authorize button lives).
    case mcpIntegrations
    case mcpServerDetail(serverId: String)
}

@MainActor
final class DeepLinkCoordinator: ObservableObject {
    static let shared = DeepLinkCoordinator()

    struct EnvVarCreate {
        let key: String
        let value: String
        let note: String

        init(key: String, value: String, note: String = "") {
            self.key = key
            self.value = value
            self.note = note
        }
    }

    /// Drives the legacy environments-with-prefill flow. The
    /// `pendingSettingsTarget = .environments` path covers the plain
    /// "open env vars" case, but a prefilled `create_key=…` link still
    /// needs to push form values into the destination view, which goes
    /// through this published EnvVarCreate.
    @Published var pendingEnvVarCreate: EnvVarCreate?

    /// When non-nil, ContentView opens the SettingsSheet (if not already
    /// open) and SettingsSheet navigates its NavigationStack to the
    /// matching destination, then clears this back to nil. `.home` opens
    /// the sheet without pushing anything.
    @Published var pendingSettingsTarget: SettingsDeepLinkTarget?

    /// Open the dedicated Rootfs Management sheet (separate from the
    /// SettingsSheet on iOS — RootfsManagementView is presented via the
    /// `activeToolSheet = .rootfsManagement` path). Mirrors Android's
    /// `Routes.ROOTFS_MANAGEMENT` route.
    @Published var pendingRootfsManagement: Bool = false

    /// Switch to a specific session. ContentView observes this and sets
    /// `selectedSessionId` to the requested id (also reloading the
    /// session list if the id isn't already loaded).
    @Published var pendingSessionId: String?

    /// When `pendingSettingsTarget == .logs`, this carries the optional
    /// `tab` query parameter from `minis://settings/logs?tab=…`. The
    /// LogManagementView reads it on appear to land on the right
    /// segmented-control tab. Cleared by the view after consumption.
    @Published var pendingLogsTab: String?

    /// [T-settings-focus-highlight] Parsed `focus=…` directives from a settings
    /// deep-link, keyed by config key. Value is the EXPECTED boolean state
    /// (`key:true`/`key:false`), or `nil` for a bare `key` (unconditional
    /// highlight). e.g. `minis://settings/background?focus=enhancedBackground
    /// Execution:true,backgroundSpeakEnabled:true`.
    ///
    /// Note the `key:value` form uses a COLON, not `=`, so the directive doesn't
    /// collide with the URL query's own `key=value` separator (a `?focus=a=true`
    /// would be ambiguous to parse / to a reader).
    ///
    /// All `focus` parsing + the highlight decision live HERE so any settings
    /// screen can opt in with one call (`shouldFocus(_:current:)`) instead of
    /// re-implementing the parsing per view. The destination view consumes this
    /// on appear (`consumeFocus()`) so a later plain navigation doesn't re-arm
    /// the borders.
    @Published var pendingFocus: [String: Bool?] = [:]

    /// Parse a raw `focus` query value (`"a:true,b,c:false"`) into directives
    /// and store them. Called by DeepLinkRouter — views never parse tokens.
    func setFocus(rawQueryValue: String?) {
        guard let raw = rawQueryValue, !raw.isEmpty else { pendingFocus = [:]; return }
        var parsed: [String: Bool?] = [:]
        for token in raw.split(separator: ",") {
            let parts = token.split(separator: ":", maxSplits: 1).map {
                $0.trimmingCharacters(in: .whitespaces)
            }
            guard let key = parts.first, !key.isEmpty else { continue }
            if parts.count == 2 {
                switch parts[1].lowercased() {
                case "true", "1":  parsed[key] = .some(true)
                case "false", "0": parsed[key] = .some(false)
                default:           parsed[key] = .some(nil)  // unrecognized → unconditional
                }
            } else {
                parsed[key] = .some(nil)                     // bare key → unconditional
            }
        }
        pendingFocus = parsed
    }

    /// Snapshot the pending focus directives and clear them (one-shot consume).
    /// Settings screens call this in `.onAppear` and hold the result locally.
    func consumeFocus() -> [String: Bool?] {
        let snapshot = pendingFocus
        pendingFocus = [:]
        return snapshot
    }

    /// Decide whether a row keyed by `key` should show the focus border given
    /// its current boolean value, per the directives in `focus` (a snapshot
    /// from `consumeFocus()`):
    ///   - bare key (value `nil`)        → always highlight
    ///   - `key=true`  (expected `true`) → highlight only while `current == false`
    ///   - `key=false` (expected `false`)→ highlight only while `current == true`
    /// Static so views can call it on their consumed snapshot without holding
    /// the coordinator.
    static func shouldFocus(_ key: String, current: Bool, in focus: [String: Bool?]) -> Bool {
        guard let expected = focus[key] else { return false }   // key not in focus set
        guard let expected else { return true }                 // bare key → unconditional
        return current != expected                              // nudge only when not yet there
    }

    @Published var showAlarmList = false
    @Published var showTerminal = false
    @Published var terminalInitCommand: String?

    // MARK: - Legacy flags (retained for binding compatibility)

    /// Legacy: tracked by SettingsSheet.onAppear to push the env-vars
    /// destination. Superseded by `pendingSettingsTarget = .environments`,
    /// kept so existing call sites keep compiling. New code should set
    /// `pendingSettingsTarget` instead.
    @Published var showEnvironmentVariables = false

    /// Legacy permissions flag — same story as
    /// `showEnvironmentVariables`. New code uses
    /// `pendingSettingsTarget = .permissions`.
    @Published var showPermissions = false
}
